"""Find Config

Revision ID: e24a023036bc
Revises: 
Create Date: 2019-04-05 11:34:31.117650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e24a023036bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activity_name'), 'activity', ['name'], unique=False)
    op.create_table('class',
    sa.Column('class_id', sa.String(length=64), autoincrement=False, nullable=False),
    sa.Column('class_name', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_index(op.f('ix_class_class_name'), 'class', ['class_name'], unique=False)
    op.create_table('doodles',
    sa.Column('doodle_id', sa.Integer(), nullable=False),
    sa.Column('foreign_answer', sa.String(), nullable=True),
    sa.Column('foreign_guess', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('doodle_id')
    )
    op.create_table('stats',
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('highest', sa.String(), nullable=True),
    sa.Column('lowest', sa.String(), nullable=True),
    sa.Column('world_rank', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('new_vocab', sa.String(), nullable=True),
    sa.Column('problem_words', sa.String(), nullable=True),
    sa.Column('most', sa.String(), nullable=True),
    sa.Column('least', sa.String(), nullable=True),
    sa.Column('activities_played', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('num_new_words', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stats_id')
    )
    op.create_table('activity_results',
    sa.Column('activity_instance_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('activity_instance_id')
    )
    op.create_index(op.f('ix_activity_results_score'), 'activity_results', ['score'], unique=False)
    op.create_table('class_configs',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('layout_data', sa.String(), nullable=True),
    sa.Column('vocab_data', sa.String(), nullable=True),
    sa.Column('unlock_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_table('class_doodles',
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('doodle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['doodle_id'], ['doodles.doodle_id'], ),
    sa.PrimaryKeyConstraint('class_id', 'doodle_id')
    )
    op.create_table('class_stats',
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.stats_id'], ),
    sa.PrimaryKeyConstraint('class_id', 'stats_id')
    )
    op.create_table('daily_class_averages',
    sa.Column('average_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('average_id')
    )
    op.create_table('find_me_configurations',
    sa.Column('find_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('items', sa.String(), nullable=True),
    sa.Column('eng_loc', sa.String(), nullable=True),
    sa.Column('for_loc', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('find_id')
    )
    op.create_table('predicted_class_averages',
    sa.Column('average_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('time_frame', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('average_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('current_class', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['current_class'], ['class.class_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('daily_averages',
    sa.Column('average_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('average_id')
    )
    op.create_table('incorrect_characters',
    sa.Column('incorrect_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('correct_letter', sa.String(length=1), nullable=True),
    sa.Column('incorrect_letter', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('incorrect_id')
    )
    op.create_table('misspelled_words',
    sa.Column('misspelled_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=30), nullable=True),
    sa.Column('translated_word', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('misspelled_id')
    )
    op.create_table('predicted_averages',
    sa.Column('average_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.Integer(), nullable=True),
    sa.Column('time_frame', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('average_id')
    )
    op.create_table('student_activity',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_instance_id'], ['activity_results.activity_instance_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'activity_instance_id')
    )
    op.create_table('student_class',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    op.create_table('student_class_level',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    op.create_table('student_doodles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doodle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doodle_id'], ['doodles.doodle_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'doodle_id')
    )
    op.create_table('student_stats',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stats_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stats_id'], ['stats.stats_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'stats_id')
    )
    op.create_table('student_vocab',
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('english', sa.String(length=120), nullable=True),
    sa.Column('translation', sa.String(length=120), nullable=True),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('vocab_id')
    )
    op.create_index(op.f('ix_student_vocab_english'), 'student_vocab', ['english'], unique=False)
    op.create_index(op.f('ix_student_vocab_translation'), 'student_vocab', ['translation'], unique=False)
    op.create_table('teacher_class',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.class_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'class_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_class')
    op.drop_index(op.f('ix_student_vocab_translation'), table_name='student_vocab')
    op.drop_index(op.f('ix_student_vocab_english'), table_name='student_vocab')
    op.drop_table('student_vocab')
    op.drop_table('student_stats')
    op.drop_table('student_doodles')
    op.drop_table('student_class_level')
    op.drop_table('student_class')
    op.drop_table('student_activity')
    op.drop_table('predicted_averages')
    op.drop_table('misspelled_words')
    op.drop_table('incorrect_characters')
    op.drop_table('daily_averages')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('predicted_class_averages')
    op.drop_table('find_me_configurations')
    op.drop_table('daily_class_averages')
    op.drop_table('class_stats')
    op.drop_table('class_doodles')
    op.drop_table('class_configs')
    op.drop_index(op.f('ix_activity_results_score'), table_name='activity_results')
    op.drop_table('activity_results')
    op.drop_table('stats')
    op.drop_table('doodles')
    op.drop_index(op.f('ix_class_class_name'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_activity_name'), table_name='activity')
    op.drop_table('activity')
    # ### end Alembic commands ###
